name: 1 [CI] PR checks

on:
  pull_request:
    branches-ignore:
      - docs

permissions: write-all

jobs:
  add-labels:
    name: Add labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

